<?php

namespace AppBundle\Repository;

/**
 * SocialUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialUserRepository extends \Doctrine\ORM\EntityRepository
{
}
