<?php

namespace AppBundle\Repository;

/**
 * VkUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VkUserRepository extends \Doctrine\ORM\EntityRepository
{
}
