<?php

namespace AppBundle\Repository;

/**
 * WorkSpaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkSpaceRepository extends \Doctrine\ORM\EntityRepository
{
}
